apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
  labels:
    app: combined-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
  template:
    metadata:
      labels:
        app: combined-app
    spec:
      containers:
      - name: mysqldb
        image: mysql:8.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "tpfoyer_db"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      - name: tp-foyer
        image: alachebil/tp-foyer:1.0.0
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{
            "spring.datasource.url"  : "jdbc:mysql://localhost:3306/tpfoyer_db?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: combined-app-service
spec:
  selector:
    app: combined-app
  ports:
    - name: http-port
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
